[package]
name = "rustcrypto-wasm"
version = "0.3.0"
authors = ["Sensei <https://github.com/SenseiDeElite>"]
description = "WebAssembly RustCrypto"
license = "MIT"
repository = "https://github.com/SenseiDeElite/agecord/tree/main/rustcrypto-wasm"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen       = "0.2.126"
getrandom          = { version = "0.4.3", features = ["wasm_js"] }

chacha20poly1305   = { version = "0.11.0", features = ["getrandom"] }
shake              = "0.1.0"
argon2             = { version = "0.5.3", default-features = false, features = ["alloc"] }
ml-dsa             = { version = "0.1.1", features = ["rand_core"] }
zeroize            = "1.9.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O4",
    "--enable-bulk-memory", 
    "--enable-simd",
    "--generate-global-effects",
    "--monomorphize",
    "-O4",
    "--flexible-inline-max-function-size", "4294967295",
    "--converge"
]
